### ISSUE TITLE
App crashes in Testflight

### ISSUE THREAD

**Issue by nyeu** [kewlbear/PythonKit#2]
Hi,

I've been able to successfully integrate it in my iOS project and works well in the simulator. On the other hand, when I archive it and open it through Testflight the app crashes. This is due that it can't find any Python library, which makes sense. How can I resolve this issue? Should I just include the whole python library in the project and put that as a path?

Thank you.

**Comment by kewlbear** [comment]
See my Python-iOS Swift package: https://github.com/kewlbear/Python-iOS.  By the way you should use https://github.com/pvieito/PythonKit, not this repo.

**Comment by nyeu** [comment]
I already included Python-iOS as part of my Swift package modules and still crashes, is there anything else I should do? I also do `PythonSupport.initialize()` before anything else.

But your repo is for iOS right? While the other one seems to be for macOS.

Thank you

**Comment by kewlbear** [comment]
See https://github.com/kewlbear/PythonPlayground/issues/2#issuecomment-835925337. And original PythonKit repo have merged my changes, so it's for any OS.
